name: verifi_lint_rules
environment:
  sdk: ">=3.2.5 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  analyzer: ^6.2.0
  analyzer_plugin: ^0.11.0
  custom_lint_builder: ^0.5.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
